apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dspark.fullname" . }}-serve
  labels:
    {{- include "dspark.labels" . | nindent 4 }}
data:
  serve.sh: |-
{{ .Files.Get "files/serve.sh" | indent 4 }}
  wait-for-worker.sh: |-
{{ .Files.Get "files/wait-for-worker.sh" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dspark.fullname" . }}-hotfixes
  labels:
    {{- include "dspark.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/hotfixes/hotfix-*" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dspark.fullname" . }}-hotfixes-vision
  labels:
    {{- include "dspark.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/hotfixes/vision_exp/*" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
